// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbAZLmlBkxoIbDIVbXNdbgIODu-uGP5D4',
    appId: '1:813048114703:web:f6ac7b04081d968c907d7a',
    messagingSenderId: '813048114703',
    projectId: 'auth-24f5a',
    authDomain: 'auth-24f5a.firebaseapp.com',
    databaseURL: 'https://auth-24f5a-default-rtdb.firebaseio.com',
    storageBucket: 'auth-24f5a.appspot.com',
    measurementId: 'G-MXMGTYNWH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqmmMAdi2mvy1I1y2VsevEO1yx-haIlUs',
    appId: '1:813048114703:android:314f6820351fb2da907d7a',
    messagingSenderId: '813048114703',
    projectId: 'auth-24f5a',
    databaseURL: 'https://auth-24f5a-default-rtdb.firebaseio.com',
    storageBucket: 'auth-24f5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAknsu5dIxJADmds-p5xV5UyR6oRupTiAo',
    appId: '1:813048114703:ios:205b08371580bb72907d7a',
    messagingSenderId: '813048114703',
    projectId: 'auth-24f5a',
    databaseURL: 'https://auth-24f5a-default-rtdb.firebaseio.com',
    storageBucket: 'auth-24f5a.appspot.com',
    iosClientId: '813048114703-vjm95tfj2vp0v0iguhlq9rl7180m9pim.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAknsu5dIxJADmds-p5xV5UyR6oRupTiAo',
    appId: '1:813048114703:ios:205b08371580bb72907d7a',
    messagingSenderId: '813048114703',
    projectId: 'auth-24f5a',
    databaseURL: 'https://auth-24f5a-default-rtdb.firebaseio.com',
    storageBucket: 'auth-24f5a.appspot.com',
    iosClientId: '813048114703-vjm95tfj2vp0v0iguhlq9rl7180m9pim.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleFirebaseAuth',
  );
}
